baseURL = '/'
languageCode = 'en-us'
title = 'share'
description = 'Social media share buttons for Hugo.'

[params]
    [params.share]
            popup = true
        [params.window]
            height = 500
            width = 500
        [params.share.facebookMessenger]
            appId = '12345678'
        [params.share.twitter]
            accountHandle = 'twitterdev'
            relatedAccounts = ['twitter']
        [params.share.vk]
            noParse = true
            noVKLinks = true
